### ISSUE TITLE
User Flow 정리 및 세부 시나리오 작성

### ISSUE THREAD

**Issue by seo2im** [seo2im/reserve42#1]
## User Flow 정리 및 세부 시나리오 작성
User flow를 그려보고 해당 과정에서 나오는 기능 시나리오를 작성할 것

### Todo
- [x] User 설정
- [x] User의 요구사항 작성
- [x] User당 User Flow 작성
- [x] User flow의 기능별 세부 시나리오 작성

**Comment by seo2im** [comment]
User설정 / 요구사항 / Flow
![제목_없는_아트워크](https://user-images.githubusercontent.com/73334068/116646160-5e855000-a9b2-11eb-91a5-725b2bd1cfab.png)

세부 시나리오 https://hackmd.io/7dkY3YBeTr-0qACeYwV2dA

## 공통 기능

### 새 이벤트 등록
개요: 새로운 이벤트를 등록하고 공간을 예약한다
사전 조건: 로그인 후 메인페이지에서 접속한다

기본흐름
1. 사용자는 새 이벤트 등록을 누른다
2. 사용자는 이벤트 이름을 등록한다
3. 사용자는 이벤트 공간을 선택한다
4. 사용자는 가능한 시간중 예약할 시간을 정한다
5. 사용자는 저장을 누른다
6. 서비스는 예약상황을 DB에 저장한다
7. 서비스는 예약 확인 페이지로 이동한다
8. 사용자는 예약을 확인한다
9. 사용자는 메인페이지로 이동한다

대체흐름
5a 저장 타이밍에 시간이 겹치는 경우
5a.1 서비스는 이미 등록된 시간이라는 메시지를 띄운다
5a.2 서비스는 예약현황을 DB로부터 갱신한다
5a.3 3로 돌아간다

### 예약 취소
개요: 본인의 예약을 확인할 수 있다
사전조건: 로그인 후 메인페이지에서 접속한다

기본흐름
1. 사용자는 마이페이지로 들어간다
2. 서비스는 사용자의 정보를 DB에서 가져온다
3. 서비스는 사용자의 예약 현황을 띄워준다
4. 사용자는 특정 예약의 예약취소 버튼을 누른다
5. 서비스는 한번더 확인한다
6. 사용자는 확인을 누른다
7. 서비스는 DB에서 예약정보를 지운다
8. 서비스는 마이페이지를 redirection한다

### 예약 현황 보기
개요: 예약의 상황을 본다
사전조건: `signIn/signUp`에 성공한 후 동작한다

기본흐름
1. 사용자는 사용자 메인페이지로 이동한다
2. 서비스는 현 모든 예약 상황을 DB에서 가져온다
3. 서비스는 모든 예약이벤트를 화면에 띄워준다


## Cadet

### SignIN
개요: 사용자가 서비스를 사용할 수 있게 로그인 한다
사전 조건: 42 seoul 멤버일 것

기본흐름
1. 사용자는 어플리케이션을 접속한다
2. 서비스는 42auth를 확인한다
3. 서비스는 auth에서 받은 정보로 DB User가 Cadet인지를 확인한다
4. `예약 현황보기`로 이동한다

대체흐름
2a DB에 user가 없는 경우
2a.1 `SignUP`으로 이동한다


### SignUP
개요: 최초 접속한 사용자의 정보를 DB에 저장한다
사전 조건: 42 seoul 멤버일 것, 처음으로 서비스를 사용할 것

기본 흐름
1. 서비스는 42Auth로 날아온 데이터의 login정보와 토큰을 DB User에 저장한다
2. `예약 현황보기`로 이동한다

## Admin

### SignIn
개요: 사용자가 서비스를 사용할 수 있게 로그인 한다
사전조건: Admin 유저이다, user DB에 admin으로 등록되어 있다

기본흐름
1. 사용자는 어플리케이션을 접속한다
2. 서비스는 42auth를 확인한다
3. 서비스는 auth에서 받은 정보로 DB User가 Admin인지 확인한다
5. `예약 현황보기`로 이동한다

### 예약 현황 보기
개요: 예약의 상황을 본다
사전조건: Admin `SignIn`에 성공한 후 동작한다

기본흐름
1. 사용자는 어드민 메인페이지로 이동한다
2. 서비스는 현 모든 예약 상황을 DB에서 가져온다
3. 서비스는 모든 예약이벤트를 취소버튼과 함께 화면에 띄워준다

### 예약 강제 취소
개요: 특정 예약을 강제 취소할 수 있다
사전조건: `admin` 로그인 후 메인페이지에서 접속한다

기본흐름
1. 사용자는 취소할 예약을 선택한다
2. 사용자는 취소 이유를 작성한다
3. 사용자는 취소 확인을 한다
4. 서비스는 예약상황을 DB에서 지운다
5. 서비스는 취소된 예약 당사자(다른 사용자)에게 이유를 전달한다(메일 or slack)
6. 사용자는 메인페이지로 이동한다
