### ISSUE TITLE
개발 환경 세팅

### ISSUE THREAD

**Issue by seo2im** [seo2im/reserve42#5]
## 개발 환경 세팅
<planning>
개발 환경 수립 및 세팅

### Todo
- [ ] 어떤 개발환경을 사용할지 결정(SSR vs Server + SPA)
- [ ] 개발 프레임워크 선정
- [ ] master branch에 개발 환경 세팅
